// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE9X1q_dP_vgQdWBcXF-QzIVcMUg15A7Q',
    appId: '1:842443400568:web:d9211fe7de5c870446948d',
    messagingSenderId: '842443400568',
    projectId: 'alsharq-76f89',
    authDomain: 'alsharq-76f89.firebaseapp.com',
    storageBucket: 'alsharq-76f89.firebasestorage.app',
    measurementId: 'G-6WKH848Z71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpjb_AYrhzoZ5xdM9TCJZsWTYrwV1Lja0',
    appId: '1:842443400568:android:cd08c2e009d3960346948d',
    messagingSenderId: '842443400568',
    projectId: 'alsharq-76f89',
    storageBucket: 'alsharq-76f89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoRj0-6dTIO2fn_plasdtMWGTk-JjRvRs',
    appId: '1:842443400568:ios:93208e6f18443f1f46948d',
    messagingSenderId: '842443400568',
    projectId: 'alsharq-76f89',
    storageBucket: 'alsharq-76f89.firebasestorage.app',
    iosBundleId: 'com.eaglines.alSharqConference',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoRj0-6dTIO2fn_plasdtMWGTk-JjRvRs',
    appId: '1:842443400568:ios:93208e6f18443f1f46948d',
    messagingSenderId: '842443400568',
    projectId: 'alsharq-76f89',
    storageBucket: 'alsharq-76f89.firebasestorage.app',
    iosBundleId: 'com.eaglines.alSharqConference',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE9X1q_dP_vgQdWBcXF-QzIVcMUg15A7Q',
    appId: '1:842443400568:web:f965b5796b346cb646948d',
    messagingSenderId: '842443400568',
    projectId: 'alsharq-76f89',
    authDomain: 'alsharq-76f89.firebaseapp.com',
    storageBucket: 'alsharq-76f89.firebasestorage.app',
    measurementId: 'G-64FQDT2BK7',
  );

}